cos/urls.py
from django.urls import path
from cos.apps import CosConfig
from . import views
from .views import *

urlpatterns = [
    path('ordens/', views.ordens, name='ordem_lista'),
    path('nova-os/', views.nova_ordem, name='nova_ordem'),
    path('ordem-criar/', views.ordem_criar, name='ordem_criar'),
    path('ordem-consulta/', views.ordem_consultar, name='ordem_consultar'),
    path('ordem-info/<str:pk>', views.ordem_info, name='ordem_info'),
    path('ordem-remover/<str:pk>', OrdemRemover.as_view(), name='ordem_remover'),
    path('ordem-atualizar/<str:pk>', OrdemAtualizar.as_view(), name='ordem_atualizar'),
    path('ordem-imprimir/<str:pk>', OrdemImprimir.as_view(), name='ordem_imprimir'),
    path('ordem-atualizar-status/<str:pk>', OrdemStatusAtualizar.as_view(), name='ordem_status_atualizar'),

    path('marca-criar/', views.marca_criar, name='marca_criar'),


]

cosmos/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('empresa/', include('empresa.urls')),
    path('cos/', include('cos.urls')),

	path('register/', users_views.register, name='register'),
	path('perfil/', users_views.perfil, name='perfil'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.urls import path
from empresa.apps import EmpresaConfig
from . import views
from .views import *

urlpatterns = [
    path('ativar/', views.empresa_criar, name='empresa_criar'),
    path('empresas/', views.empresas, name='empresa_lista'),
    path('painel/<int:pk>', views.empresa_painel, name='empresa_painel'),

    path('cliente-criar/', views.cliente_criar, name='cliente_criar'),
    path('cliente-criar-extendido/', views.cliente_criar_ex, name='cliente_criar_ex'),
    path('novo-cliente/', views.novo_cliente, name='novo_cliente'),
    path('cliente-remover/<int:pk>', ClienteRemover.as_view(), name='cliente_remover'),
    path('clientes/', views.clientes, name='cliente_lista'),

]

empresa/models.py
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.models import PermissionsMixin
from PIL import Image
import random

UF_CHOICES = (
		('AC', 'Acre'), 
		('AL', 'Alagoas'),
		('AP', 'Amapá'),
		('BA', 'Bahia'),
		('CE', 'Ceará'),
		('DF', 'Distrito Federal'),
		('ES', 'Espírito Santo'),
		('GO', 'Goiás'),
		('MA', 'Maranão'),
		('MG', 'Minas Gerais'),
		('MS', 'Mato Grosso do Sul'),
		('MT', 'Mato Grosso'),
		('PA', 'Pará'),
		('PB', 'Paraíba'),
		('PE', 'Pernanbuco'),
		('PI', 'Piauí'),
		('PR', 'Paraná'),
		('RJ', 'Rio de Janeiro'),
		('RN', 'Rio Grande do Norte'),
		('RO', 'Rondônia'),
		('RR', 'Roraima'),
		('RS', 'Rio Grande do Sul'),
		('SC', 'Santa Catarina'),
		('SE', 'Sergipe'),
		('SP', 'São Paulo'),
		('TO', 'Tocantins'),
	)

NIVEL_CHOICES = (
		(0, 'Gerente'),
		(1, 'Técnico'), 
		(2, 'Operador'),
		)

class Empresa(models.Model):
	dono = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Dono')
	logo = models.ImageField(_('Logo'), default='default.jpg', upload_to='negocio_pics')
	nome_fantasia = models.CharField(_('Nome fantasia'), max_length=40, null=False, blank=False)
	nome_unico = models.CharField(_('Identificação Única Cosmos'), max_length=20, unique=True, null=True, blank=False)
	identificacao = models.CharField(_('CPF/CNPJ'), max_length=18, null=False, blank=False)
	telefone = models.CharField(_('Telefone'), max_length=20, null=False, blank=True)
	celular = models.CharField(_('Celular'), max_length=20, null=False, blank=False)
	email = models.CharField(_('E-mail'), max_length=60, null=True, blank=True)
	cep = models.CharField(_('CEP'),max_length=8, null=False, blank=False)
	endereco = models.CharField(_('Endereço'), max_length=200, null=False, blank=False)
	numero = models.IntegerField(_('Número'), null=False, blank=False)
	complemento = models.CharField(_('Complemento'),max_length=20, null=True, blank=True)
	bairro = models.CharField(_('Bairro'),max_length=100, null=False, blank=False)
	cidade = models.CharField(_('Cidade'),max_length=100, null=False, blank=False)
	uf = models.CharField(_('Estado'),max_length=2, null=False, blank=False, choices=UF_CHOICES, default='MG')
	#Metadata
	data = models.DateField(default=timezone.now)
	completo = models.BooleanField(_('Completo'), default=False)

	def __str__(self):
		return f'{self.nome_fantasia} - {self.identificacao}'

	def endereco_completo(self):
		return f'{self.endereco}, {self.numero}, {self.bairro} - {self.cidade}/{self.uf}'

class Colaborador(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Colaborador')
	nivel = models.CharField(_('Nível'),max_length=2, null=False, blank=False, choices=NIVEL_CHOICES, default=0)
	#Metadata
	empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Empresa', null=True, blank=True)
	data = models.DateField(default=timezone.now)

	def __str__(self):
		return f'{self.user}'

class Cliente(models.Model):
	nome = models.CharField(_('Nome completo'), max_length=60, null=False, blank=False)
	identificacao = models.CharField(_('CPF/CNPJ'), max_length=14, null=False, blank=False)
	telefone = models.CharField(_('Telefone'), max_length=20, null=False, blank=True)
	celular = models.CharField(_('Celular'), max_length=20, null=False, blank=False)
	cep = models.CharField(_('CEP'),max_length=8, null=False, blank=False)
	endereco = models.CharField(_('Endereço'), max_length=200, null=False, blank=False)
	numero = models.IntegerField(_('Número'), null=False, blank=False)
	complemento = models.CharField(_('Complemento'),max_length=20, null=True, blank=True)
	bairro = models.CharField(_('Bairro'),max_length=100, null=False, blank=False)
	cidade = models.CharField(_('Cidade'),max_length=100, null=False, blank=False)
	uf = models.CharField(_('Estado'),max_length=2, null=False, blank=False, choices=UF_CHOICES, default='MG')
	#Metadata
	data = models.DateField(default=timezone.now)
	vinculo = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Vinculado a', null=True, blank=False)

	def __str__(self):
		return f'{self.nome}'

	def get_identificacao(self):
		cid = self.identificacao
		if len(cid) < 12:
			cid = '{}.{}.{}-{}'.format(cid[:3], cid[3:6], cid[6:9], cid[9:])
			return cid
		else:
			cid = '{}.{}.{}/{}-{}'.format(cid[:2], cid[2:5], cid[5:8], cid[8:12], cid [12:])
			return cid
		return cid

	def get_endereco(self):
		if self.complemento != None and len(self.complemento) > 0:
			endereco = '%s, %s, %s, %s - %s/%s' % (self.endereco, self.numero, self.complemento, self.bairro, self.cidade, self.uf)
		else:
			endereco = '%s, %s, %s - %s/%s' % (self.endereco, self.numero, self.bairro, self.cidade, self.uf)
		return endereco.strip()
		

class ColaboradorConvite(models.Model):
	convidado = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuário convidado', null=True, blank=True)
	empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Empresa', null=True, blank=True)

	def __str__(self):
		return f'{self.convidado} para ser colaborador de {self.empresa}'

empresa/forms.py
from django import forms
from django.contrib.auth.models import User
from localflavor.br.forms import *
from .models import *

class EmpresaCriarForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = Empresa
		fields = ['logo', 'nome_fantasia', 
		'identificacao', 'telefone',
		'celular', 'email', 'cep',
		'endereco', 'numero',
		'complemento', 'bairro',
		'cidade', 'uf',]

class ColaboradorNivelForm(forms.ModelForm):

	class Meta:
		model = Colaborador
		fields = ['nivel']

class ClienteForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = Cliente
		fields = ['nome', 
		'telefone', 'celular',
		'email', 'cep',
		'endereco', 'numero',
		'complemento', 'bairro',
		'cidade', 'uf',]

empresa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (
	ListView, 
	DetailView, 
	UpdateView, 
	CreateView,
	DeleteView,
	TemplateView
	)
from .forms import *
from .models import *
from users.models import Controle
from cos.models import Ordem


@login_required
def empresa_criar(request):
	if request.method =='POST':
		form=EmpresaCriarForm(request.POST, request.FILES)
		if form.is_valid():
			form.instance.dono = request.user
			form.instance.ativo = True
			form.save()
			messages.success(request, f'Empreendimento cadastrado com sucesso!')
			return redirect('empresa_lista')
	else:
		form=EmpresaCriarForm()

	return render(request, 'empresa/empresa_ativar.html', {'form': form})


def empresa_atualizar(request):
	return 0

@login_required
def empresa_painel(request, pk):
	#Seleciona empresa para tarefas
	empresa = Empresa.objects.get(pk=pk)
	Controle.objects.filter(user=request.user).update(empresa_selecionada=empresa)
	#Seleciona OSs da empresa
	ordens = Ordem.objects.filter(empresa=empresa).order_by('-data')[:3]
	colaboradores = Colaborador.objects.filter(empresa=empresa)

	cxt={'ordens':ordens, 'colaboradores':colaboradores}

	return render(request, 'empresa/empresa_painel.html', cxt)

def empresa_desativar(request):
	return 0

@login_required
def empresas(request):
	empresas_usuario = Empresa.objects.filter(dono=request.user)

	return render(request, 'empresa/empresa_lista.html', {'empresas_usuario': empresas_usuario})

def colaboradores(request):
	return 0

@login_required
def clientes(request):
	clientes = Cliente.objects.filter(vinculo=request.user.controle.empresa_selecionada)
	empresa = request.user.controle.empresa_selecionada
	numero_clientes = len(clientes)
	return render(request, 'empresa/cliente_lista.html', {'empresa': empresa, 'clientes': clientes, 'numero_clientes':numero_clientes})

@login_required
def cliente_criar_ex(request):
	if request.method =='POST':
		form=ClienteForm(request.POST)
		if form.is_valid():
			form.instance.vinculo = request.user.empresa
			form.instance.identificacao = request.session['cid']
			form.instance.ativo = True
			form.save()
			messages.success(request, f'Cliente cadastrado com sucesso!')

			cliente = Cliente.objects.get(identificacao=request.session['cid'])
			empresa = Empresa.objects.get(pk=request.user.controle.empresa_selecionada.pk)

			request.session['cliente'] = cliente.id
			request.session['empresa'] = empresa.id

			return redirect('ordem_criar')
	else:
		form=ClienteForm()
		cid = request.session['cid']
		if len(cid) < 12:
			cid = '{}.{}.{}-{}'.format(cid[:3], cid[3:6], cid[6:9], cid[9:])
		else:
			cid = '{}.{}.{}/{}-{}'.format(cid[:2], cid[2:5], cid[5:8], cid[8:12], cid [12:])

	return render(request, 'empresa/cliente_criar.html', {'form': form, 'cid': cid})

@login_required
def cliente_criar_ex(request):
	if request.method =='POST':
		form=ClienteForm(request.POST)
		if form.is_valid():
			form.instance.vinculo = request.user.empresa
			form.instance.identificacao = request.session['cid']
			form.instance.ativo = True
			form.save()
			messages.success(request, f'Cliente cadastrado com sucesso!')

			cliente = Cliente.objects.get(identificacao=request.session['cid'])
			empresa = Empresa.objects.get(pk=request.user.controle.empresa_selecionada.pk)

			request.session['cliente'] = cliente.id
			request.session['empresa'] = empresa.id

			return redirect('ordem_criar')
	else:
		form=ClienteForm()
		cid = request.session['cid']
		if len(cid) < 12:
			cid = '{}.{}.{}-{}'.format(cid[:3], cid[3:6], cid[6:9], cid[9:])
		else:
			cid = '{}.{}.{}/{}-{}'.format(cid[:2], cid[2:5], cid[5:8], cid[8:12], cid [12:])

	return render(request, 'empresa/cliente_criar_ex.html', {'form': form, 'cid': cid})

@login_required
def cliente_criar(request):
	if request.method =='POST':
		form=ClienteForm(request.POST)
		if form.is_valid():
			form.instance.vinculo = request.user.empresa
			form.instance.identificacao = request.session['new_cid']
			form.instance.ativo = True
			form.save()
			messages.success(request, f'Cliente cadastrado com sucesso!')

			cliente = Cliente.objects.get(identificacao=request.session['new_cid'])
			empresa = Empresa.objects.get(pk=request.user.controle.empresa_selecionada.pk)

			request.session['cliente'] = cliente.id
			request.session['empresa'] = empresa.id

			return redirect('cliente_lista')
	else:
		form=ClienteForm()
		new_cid = request.session['new_cid']
		if len(new_cid) < 12:
			new_cid = '{}.{}.{}-{}'.format(new_cid[:3], new_cid[3:6], new_cid[6:9], new_cid[9:])
		else:
			new_cid = '{}.{}.{}/{}-{}'.format(new_cid[:2], new_cid[2:5], new_cid[5:8], new_cid[8:12], new_cid [12:])

	return render(request, 'empresa/cliente_criar.html', {'form': form, 'new_cid': new_cid})


class ClienteRemover(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Cliente
	login_required = True
	template_name = 'empresa/cliente_remover.html'

	def test_func(self):
		if self.request.user == self.request.user.empresa.dono:
			return True
		if Colaborador.objects.get(user=self.request.user):
			return True
		return False

	def get_success_url(self):
		return reverse('cliente_lista')

@login_required
def novo_cliente(request):
	if request.method == 'GET':
		clientes = Cliente.objects.all()
		return render(request, 'empresa/novo_cliente.html', {'clientes': clientes})
	#elif request.POST['action'] == 'consultaPorId':
	else:
		new_cid = request.POST.get('clienteID', None)
		valida_id = len(new_cid)
		if valida_id == 11 or valida_id == 14:
			if Cliente.objects.filter(identificacao=new_cid, vinculo=request.user.controle.empresa_selecionada):

				cliente = Cliente.objects.get(identificacao=new_cid)
				empresa = Empresa.objects.get(pk=request.user.controle.empresa_selecionada.pk)

				request.session['cliente'] = cliente.id
				request.session['empresa'] = empresa.id

				return redirect('ordem_criar')

			else:
				request.session['new_cid'] = new_cid
				return redirect('cliente_criar')
		else:
			messages.success(request, f'CPF/CNPJ Inválido')
			return redirect('novo_cliente')

empresa/templates/empresa/cliente_criar.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="features-boxed">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Cadastrar Cliente</h2>
            <p class="text-center">Cadastro de cliente para o CPF/CNPJ: {{ new_cid }} <a class="btn" href="{% url 'novo_cliente' %}"><i class="fas fa-exchange-alt"></i></a></p>
            </div>
            <form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}					
			</fieldset>
			<div class="form-group" align="center">
				<button class="btn btn-primary" type='submit'>Cadastrar</button>
			</div>
			<br>
		</form>
</div>
</div>

<!-- JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<script type="text/javascript">
	$("#id_cep").focusout(function(){
		$.ajax({
			url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/unicode/',
			dataType: 'json',
			success: function(resposta){
				$("#id_endereco").val(resposta.logradouro);
				$("#id_bairro").val(resposta.bairro);
				$("#id_cidade").val(resposta.localidade);
				$("#id_uf").val(resposta.uf);
				$("#numero").focus();
			}
		});
	});
</script>

{% endblock content %}

empresa/templates/empresa/cliente_criar_ex.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="features-boxed">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Cadastrar Cliente</h2>
            <p class="text-center">Cadastro de cliente para o CPF/CNPJ: {{ cid }}</p>
            </div>
            <form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}					
			</fieldset>
			<div class="form-group" align="center">
				<button class="btn btn-primary" type='submit'>Cadastrar</button>
			</div>
			<br>
		</form>
</div>
</div>

<!-- JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<script type="text/javascript">
	$("#id_cep").focusout(function(){
		$.ajax({
			url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/unicode/',
			dataType: 'json',
			success: function(resposta){
				$("#id_endereco").val(resposta.logradouro);
				$("#id_bairro").val(resposta.bairro);
				$("#id_cidade").val(resposta.localidade);
				$("#id_uf").val(resposta.uf);
				$("#numero").focus();
			}
		});
	});
</script>

{% endblock content %}

empresa/templates/empresa/cliente_lista.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="features-boxed" style="padding-bottom: 70px;">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Lista de Clientes</h2>
            <p class="text-center">{{ empresa.nome_fantasia|upper}} possui {{ numero_clientes }} cliente(s).</p>
            </div>
           <h2><a class="btn btn-primary" href="{% url 'nova_ordem' %}"><i class="far fa-plus-square"></i> Novo Cliente</a></h2>
    <table id="tabelaPedidos" class="display table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">CPF</th>
      <th scope="col">Celular</th>
      <th scope="col">Cidade</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
{% for c in clientes %}
    <tr>
      <th scope="row">{{ c.nome }}</th>
      <td>{{ c.get_identificacao }}</td>
      <td>{{ c.celular }}</td>
      <td>{{ c.cidade }} <small>({{c.uf}})</small></td>
      <td>
   <div class="dropdown no-arrow"><button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false" type="button"><i class="fas fa-ellipsis-v"></i></button>
		  <div class="dropdown-menu  dropdown-menu-right animated--fade-in" role="menu">
		    <a class="dropdown-item" role="presentation" href="#">&nbsp;Visualizar</a>
		 <a class="dropdown-item" role="presentation" href="#">&nbsp;Atualizar</a>
		  <a class="dropdown-item" role="presentation" href="{% url 'cliente_remover' c.pk %}">&nbsp;Remover</a>
			</div>

        </td>
    </tr>
  {% endfor %}
  
</tbody>
</table>
</div>
</div>


<!-- JS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
  $.noConflict();
  jQuery(document).ready( function ($) {
    $('#tabelaPedidos').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
        }
    });
} );</script>
<!-- Fim JS -->

{% endblock content %}

empresa/templates/empresa/cliente_remover.html
{% extends "website/base.html" %}

{% block content %}

<div class="features-boxed" align="center" style="padding-bottom: 100px;">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Remover Cliente</h2>

		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<h6>Você tem certeza que quer remover esse(a) Cliente? "{{ object.nome }}"</h6>
				<ul class="list-group" align="left" style="padding-inline-start: 10px!important;">
						   	<li class="list-group-item">CPF: {{ object.get_identificacao }}</li>
						</ul>	
			</fieldset>
			<div class="form-group">
				<button class="btn btn-danger" type='submit'>Sim, remover</button>
				<a class="btn btn-secondary" href="{% url 'cliente_lista' %}">Cancelar</a>
			</div>
		</form>
	</div>
</div>
</div>
{% endblock content %}

empresa/templates/empresa/empresa_ativar.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="features-boxed">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Cadastrar Empresa</h2>
            <p class="text-center">Insira os dados abaixo para cadastrar sua empresa no Cosmos.</p>
            </div>
            <form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}					
			</fieldset>
			<div class="form-group" align="center">
				<button class="btn btn-primary" type='submit'>Cadastrar</button>
			</div>
			<br>
		</form>
</div>
</div>
{% endblock content %}

empresa/templates/empresa/empresa_inativa.html
{% extends "website/base.html" %}
{% load static %}
{% block content %}


<div class="container">
<h1 class="titulo" style="text-align: center;">Iniciar Empresa</h1>
<p class="banner-p" style="text-align: center; ">Você ainda não cadastrou sua empresa no Cosmos, clique no botão abaixo para realizar seu cadastro.</p>
<p style="text-align: center; "><br><a class="button btn-primary" href="{% url 'empresa_criar' %}">INICIAR EMPRESA</a></p>
</div>

{% endblock content %}

empresa/templates/empresa/empresa_lista.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="features-boxed">
	<div class="container" align="center">
            <div class="intro">
                <h2 class="text-center" style="font-size: 20px; margin-bottom: 0px!important">Sou dono de...</h2>
            </div>
            {% if empresas_usuario|length > 0 %}
            <div class="row justify-content-center features">
            	{% for e in empresas_usuario %}
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fas fa-building icon"></i>
                        <h3 class="name">{{ e.nome_fantasia }}</h3>
                        <p class="text-center description">Situada na {{ e.endereco_completo }}</p>
                        <a class="btn btn-primary" href="{% url 'empresa_painel' e.id %}">Gerir</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <br>
            <p>Nenhuma empresa.</p>
           <a class="btn btn-primary" href="{% url 'empresa_criar' %}">Cadastrar Minha Empresa</a><br><br>
            {% endif %}

            <div class="intro">
                <h2 class="text-center" style="font-size: 20px; margin-bottom: 0px!important; padding-top: 0px!important">Sou colaborador em...</h2>
            </div><br>
            
            <p>Nenhuma empresa.</p><br><br>

</div>
</div>


{% endblock content %}

empresa/templates/empresa/novo_cliente.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="features-boxed">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Novo Cliente</h2>
            <p class="text-center">Insira o CPF/CNPJ do cliente a ser cadastrado.</p>
            </div><br><br>
           
        <div class="container" style="max-width: 800px;">
	    <form action="#" method="POST"> {% csrf_token %}
	      <div class="input-group mb-3" >
	      	 {% if messages %}
            {% for message in messages %}
            <div class="container-fluid">
              <div class="alert alert-danger">
                {{ message }}
              </div>{% endfor %}
          </div>{% endif %}
	        <div class="input-group-prepend">
	          <span class="input-group-text" id="basic-addon1">Digite o CPF/CNPJ do Cliente: </span>
	        </div>
	          <input class="form-control" type="clienteID" name="clienteID" placeholder="CPF/CNPJ" style="height: auto;" />
	        <div class="input-group-append">
	          <button class="btn btn-primary" type="submit" name="action" value="consultaPorId" >Ir &raquo;</button>
	        </div>
	      </div>
	    </form>
	</div>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br>


	</div>
</div>

{% endblock content %}