cos/urls.py
from django.urls import path
from cos.apps import CosConfig
from . import views
from .views import *

urlpatterns = [
    path('ordens/', views.ordens, name='ordem_lista'),
    path('nova-os/', views.nova_ordem, name='nova_ordem'),
    path('ordem-criar/', views.ordem_criar, name='ordem_criar'),
    path('ordem-consulta/', views.ordem_consultar, name='ordem_consultar'),
    path('ordem-info/<str:pk>', views.ordem_info, name='ordem_info'),
    path('ordem-remover/<str:pk>', OrdemRemover.as_view(), name='ordem_remover'),
    path('ordem-atualizar/<str:pk>', OrdemAtualizar.as_view(), name='ordem_atualizar'),
    path('ordem-imprimir/<str:pk>', OrdemImprimir.as_view(), name='ordem_imprimir'),
    path('ordem-atualizar-status/<str:pk>', OrdemStatusAtualizar.as_view(), name='ordem_status_atualizar'),

    path('marca-criar/', views.marca_criar, name='marca_criar'),


]

cosmos/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('empresa/', include('empresa.urls')),
    path('cos/', include('cos.urls')),

	path('register/', users_views.register, name='register'),
	path('perfil/', users_views.perfil, name='perfil'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.models import PermissionsMixin
from PIL import Image
import random
from empresa.models import Empresa
from cos.models import Ordem


class Perfil(models.Model):
	UF_CHOICES = (
		('AC', 'Acre'), 
		('AL', 'Alagoas'),
		('AP', 'Amapá'),
		('BA', 'Bahia'),
		('CE', 'Ceará'),
		('DF', 'Distrito Federal'),
		('ES', 'Espírito Santo'),
		('GO', 'Goiás'),
		('MA', 'Maranão'),
		('MG', 'Minas Gerais'),
		('MS', 'Mato Grosso do Sul'),
		('MT', 'Mato Grosso'),
		('PA', 'Pará'),
		('PB', 'Paraíba'),
		('PE', 'Pernanbuco'),
		('PI', 'Piauí'),
		('PR', 'Paraná'),
		('RJ', 'Rio de Janeiro'),
		('RN', 'Rio Grande do Norte'),
		('RO', 'Rondônia'),
		('RR', 'Roraima'),
		('RS', 'Rio Grande do Sul'),
		('SC', 'Santa Catarina'),
		('SE', 'Sergipe'),
		('SP', 'São Paulo'),
		('TO', 'Tocantins'),
	)
	SEXO_CHOICES = (
		('M', 'Masculino'),
		('F', 'Feminino'),
		('O', 'Outro'),
	)

	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Usuário')
	image = models.ImageField(_('Imagem Perfil'), default='default.jpg', upload_to='profile_pics')
	sexo = models.CharField(_('Sexo'),max_length=1, choices=SEXO_CHOICES)
	cpf = models.CharField(_('CPF'), max_length=11, null=True, blank=False)
	data_nascimento = models.DateField(default=timezone.now)
	telefone = models.CharField(_('Telefone'), max_length=20, null=True, blank=True)
	celular = models.CharField(_('Celular'), max_length=20, null=True, blank=False)
	cep = models.CharField(_('CEP'),max_length=8, null=True, blank=False)
	endereco = models.CharField(_('Endereço'), max_length=200, null=True, blank=False)
	numero = models.IntegerField(_('Número'), null=True, blank=False)
	complemento = models.CharField(_('Complemento'),max_length=30, null=True, blank=False)
	bairro = models.CharField(_('Bairro'),max_length=100, null=True, blank=False)
	cidade = models.CharField(_('Cidade'),max_length=100, null=True, blank=False)
	uf = models.CharField(_('Estado'),max_length=2, null=True, blank=False, choices=UF_CHOICES, default='MG')
	#Metadata
	completo = models.BooleanField(_('Completo'), default=False)

	def __str__(self):
		return f'{self.user.username} Perfil'

	def nome_completo(self):

		full_name = '%s %s' % (self.user.first_name, self.user.last_name)
		return full_name.strip()

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300,300)
			img.thumbnail(output_size)
			img.save(self.image.path)


class Controle(models.Model):
	PLANO_CHOICES = (
		(0, 'Gratuito'),
		(1, 'Premium'),
	)
	plano = models.IntegerField(_('Plano'), default=0, choices=PLANO_CHOICES)
	empresa_selecionada = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Empresa selecionada', null=True, blank=False)
	limite_empresas = models.IntegerField(_('Limite empresas'), null=False, blank=False, default = 1)
	limite_colaboradores = models.IntegerField(_('Limite colaboradores'), null=False, blank=False, default = 5)
	#User
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Usuário')

	def __str__(self):
		return f'Plano {self.plano}'

	def ordens_todas(self):
		ordens = Ordem.objects.filter(empresa=self.empresa_selecionada)
		return ordens

users/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from cpf_field.models import CPFField

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', \
		 'password2']

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name']

class PerfilUpdateForm(forms.ModelForm):
	cpf = CPFField(max_length=11)
	class Meta:
		model = Perfil
		fields = ['image', 'sexo', 'data_nascimento', 'cpf', 'cep', 'endereco', 'complemento', 'bairro', \
		'cidade', 'uf',]

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import *
from django.contrib.auth.decorators import login_required
from django.views.generic import (
	ListView, 
	DetailView, 
	UpdateView, 
	CreateView,
	DeleteView,
	TemplateView
	)


def register(request):
	if request.method =='POST':
		form=UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username=form.cleaned_data.get('username')
			messages.success(request, f'{username}, sua conta foi criada com sucesso! Você já pode acessar o sistema!')
			return redirect('login')
	else:
		form=UserRegisterForm()

	return render(request, 'users/register.html', {'form': form})

@login_required
def perfil(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = PerfilUpdateForm(request.POST, request.FILES, instance=request.user.perfil)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Sua conta foi atualizada!')
			return redirect('home')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = PerfilUpdateForm(instance=request.user.perfil)

	context = {
		'u_form': u_form,
		'p_form': p_form
	}

	return render(request, 'users/perfil.html', context)

users/templates/users/login.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="features-boxed" align="center">
	<div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Login</h2>
            <p class="text-center">Entre com seu Login.</p>
            </div>
		<form method="POST">
			{% csrf_token %}
			<div style="max-width: 500px; text-align: left;">
			<fieldset class="form-group">
								{{ form|crispy }}					
			</fieldset>
			</div>
			<div class="form-group">
				<button class="btn btn-primary" type='submit'>Entrar</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Primeiro acesso? <a class="ml-2" href="{% url 'register' %}">Cadastre-se</a>
			</small>
			<br><br><br><br><br><br><br><br>
		</div>
	</div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="features-boxed">
<div class="d-flex justify-content-center bd-highlight mb-3">
<div class="column" align="center">
<h2> Deseja acessar novamente?</h2>

<a class="ml-2" href="{% url 'login' %}">Acessar Novamente</a>
	</div>		
</div><br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock content %}

users/templates/users/perfil.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="d-flex justify-content-center">
	<div class="content-section" style="width: 700px;">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ user.perfil.image.url }}">
			<div class="media-body">
				<h2 class="account-heading">{{ user.perfil.nome_completo }}</h2>
				<p class="text-secondary">@{{ user.username }}</p>
			</div>
		</div>
		
<!-- Dentro daqui vai ser os colapse -->
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Perfil
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <p><b>Nome: </b>{{ user.perfil.nome_completo }}</p>
        <p><b>Data de nascimento: </b>{{ user.perfil.data_nascimento }}</p>
       <p><b>Sexo: </b>{{ user.perfil.get_sexo_display }}</p>
        <p><b>Estado Civil: </b>{{ user.perfil.get_estado_civil_display }}</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Contato
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <p><b>Telefone: </b>{{ user.perfil.contato1 }}</p>
        <p><b>Celular: </b>{{ user.perfil.contato2 }}</p>
        <p><b>E-mail: </b>{{ user.email }}</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Endereço
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <p><b>CEP: </b>{{ user.perfil.cep }}</p>
        <p><b>Endereço: </b>{{ user.perfil.endereco }}</p>
        <p><b>Bairro: </b>{{ user.perfil.bairro }}</p>
        <p><b>Cidade: </b>{{ user.perfil.cidade }}</p>
        <p><b>Estado: </b>{{ user.perfil.uf }}</p>
      </div>
    </div>
  </div>
</div>
<!-- Fim colapse -->
<div><br></div>

<button type="button" class="btn btn-info btn-circle" data-toggle="modal" data-target="#editarPerfil">
  Editar Perfil
</button>

<!-- Modal -->
<div class="modal fade" id="editarPerfil" tabindex="-1" role="dialog" aria-labelledby="editarPerfil" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editarPerfil">Editar Pefil</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border_bottom mb-4"></legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}				
			</fieldset>
			<div class="form-group">
				<button type="button" class="btn btn-outline-secondary btn-circle" data-dismiss="modal">Fechar</button>
				<button class="btn btn-outline-sucess btn-circle" type='submit'>Atualizar</button>
			</div>
		</form>	
    	  </div>
   		 </div>
		  </div>
		</div>
		
	</div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="d-flex justify-content-center">
	<div class="content-section" style="width: 700px;">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ user.perfil.image.url }}">
			<div class="media-body">
				<h2 class="account-heading">{{ user.perfil.nome_completo }}</h2>
				<p class="text-secondary">@{{ user.username }}</p>
			</div>
		</div>
		
<!-- Dentro daqui vai ser os colapse -->
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Perfil
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <p><b>Nome: </b>{{ user.perfil.nome_completo }}</p>
        <p><b>Data de nascimento: </b>{{ user.perfil.data_nascimento }}</p>
       <p><b>Sexo: </b>{{ user.perfil.get_sexo_display }}</p>
        <p><b>Estado Civil: </b>{{ user.perfil.get_estado_civil_display }}</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Contato
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <p><b>Telefone: </b>{{ user.perfil.contato1 }}</p>
        <p><b>Celular: </b>{{ user.perfil.contato2 }}</p>
        <p><b>E-mail: </b>{{ user.email }}</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Endereço
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <p><b>CEP: </b>{{ user.perfil.cep }}</p>
        <p><b>Endereço: </b>{{ user.perfil.endereco }}</p>
        <p><b>Bairro: </b>{{ user.perfil.bairro }}</p>
        <p><b>Cidade: </b>{{ user.perfil.cidade }}</p>
        <p><b>Estado: </b>{{ user.perfil.uf }}</p>
      </div>
    </div>
  </div>
</div>
<!-- Fim colapse -->
<div><br></div>

<button type="button" class="btn btn-info btn-circle" data-toggle="modal" data-target="#editarPerfil">
  Editar Perfil
</button>

<!-- Modal -->
<div class="modal fade" id="editarPerfil" tabindex="-1" role="dialog" aria-labelledby="editarPerfil" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editarPerfil">Editar Pefil</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border_bottom mb-4"></legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}				
			</fieldset>
			<div class="form-group">
				<button type="button" class="btn btn-outline-secondary btn-circle" data-dismiss="modal">Fechar</button>
				<button class="btn btn-outline-sucess btn-circle" type='submit'>Atualizar</button>
			</div>
		</form>	
    	  </div>
   		 </div>
		  </div>
		</div>
		
	</div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="features-boxed" align="center">
	<div class="container">
		<form method="POST">
			<div style="max-width: 500px; text-align: left;">
			{% csrf_token %}
			<fieldset class="form-group">
				<div class="intro">
                <h2 class="text-center" style="font-size: 30px;">Cadastre-se!</h2>
            <p class="text-center">Realize o seu cadastro para ter acesso as funcionalidades da nossa plataforma.</p>
            </div>
				{{ form|crispy }}	
				</div>				
			</fieldset>
			<div class="form-group">
				<button class="btn btn-primary" type='submit'>Cadastrar</button>
			
		</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Já tem uma conta? <a class="ml-2" href="{% url 'login' %}">Entrar</a><br><br>
			</small>

</div>
</div>
</div>
{% endblock content %}